
server:
  port: 8180

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanger
    username: root
    password: 1234

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.weblean4.pojo
  configuration:
    map-underscore-to-camel-case: true



